version: "4.0"

networks:
  blue_team_net:
    driver: bridge
    name: blue_team_net

services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    networks:
      - blue_team_net
    depends_on:
      - dvwa_db
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - MYSQL_HOST=dvwa_db
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa

  dvwa_db:
    image: mysql:5.7
    container_name: dvwa_db
    networks:
      - blue_team_net
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa
    volumes:
      - dvwa_db_data:/var/lib/mysql
    restart: unless-stopped

  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    networks:
      - blue_team_net
    ports:
      - "2222:2222"
    environment:
      - COWRIE_TTYLOG_ENABLED="true"
      - COWRIE_DOWNLOADS_ENABLED="true"
      - COWRIE_SSH_LISTEN_PORT="2222"
      - COWRIE_TELNET_ENABLED="false"
      - COWRIE_HOSTNAME="ssh-server"
      - COWRIE_SSH_VERSION="SSH-2.0-OpenSSH_8.9p1"
      - COWRIE_USERDB_ENABLED="true"
    volumes:
      - cowrie_data:/cowrie/var
      - cowrie_cfg:/cowrie/etc
    restart: unless-stopped

  smb:
    image: demisto/smb:latest
    container_name: smb
    hostname: smb
    detach: true
    restart: always

  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      - NAME="Data"
      - USER="samba"
      - PASS="habit's smb server"
    ports:
      - "445:445"
    volumes:
      - ./samba:/storage
    restart: always

volumes:
  dvwa_db_data:
  cowrie_data:
  cowrie_cfg:
